on:
  push:
    tags:
      - v*
jobs:
  release_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JAVA 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}


      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.TINY_DICT_SIGNING_KEY_BASE64 }}
        run: | 
          echo "$ENCODED_STRING" > keystore-base64.txt 
          base64 -d keystore-base64.txt > keystore.jks


      - name: Make gradlew executable
        run: chmod +x ./gradlew


      - name: Build Release apk
        env:
          TINY_DICT_KEY_ALIAS: ${{ secrets.TINY_DICT_KEY_ALIAS }}
          TINY_DICT_KEYSTORE_PASSWORD: ${{ secrets.TINY_DICT_KEYSTORE_PASSWORD }}
          DICT_API_KEY: ${{ secrets. DICT_API_KEY}}

        run: |
          export TINY_DICT_PASSWORD=${{ secrets.TINY_DICT_PASSWORD }}
          export TINY_DICT_ALIAS=${{ secrets.TINY_DICT_ALIAS }}
          ./gradlew assembleRelease


      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Builds
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: warn

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Tiny Dict releases"
          files: app/build/outputs/apk/release/*.apk
